### PR TITLE
Silicon SCF example

### PR DESCRIPTION
**Pull request by antoine-levitt**
This is for the paper with Gaspard and Eric. We can put it in another folder if we don't want it to be run by CI; alternatively I could put it in another repo but it's a neat self-contained example and illustrates callbacks so it's nice to have it here.

### CODE REVIEW

**Comment by mfherbst** [comment]
If you don't want it to run by CI just add a comment line:
```
## tags: long
```
Also it uses PyPlot, which we gave up on ...

**Comment by mfherbst** [comment]
But in this case there is no reason to use PyPlot, if you're saving the figures anyway... I'd stick to Plots.

**Comment by mfherbst** [comment]
Oh and multiple windows in Plots you get by the kwarg `reuse=false`.

**Comment by mfherbst** [comment]
Why no savefig now? And thanks for using Plots ;)

**Comment by antoine-levitt** [comment]
Doesn't matter for the savefig...
Let's keep this PR open until we submit and have an arxiv number (shouldn't be long)

**Comment by mfherbst** [comment]
Sure. I guess we want to have a nice page in our docs with related publications anyway ;).

**Comment by mfherbst** [comment]
By the way: Do you also refer to this code inside the paper (with a footnote or so) ... could help to get people take a look at DFTK?

**Comment by antoine-levitt** [comment]
Sure, it's as a ref with the URL. I did not put the zenodo there though

**Comment by antoine-levitt** [comment]
The arxiv link is in, so that's good to go for me

**Pull request merged**
