### PR TITLE
Definitions, normalizations, etc.

### PR DESCRIPTION
**Pull request by antoine-levitt**

### CODE REVIEW

**Comment by antoine-levitt** [comment]
Should we commit the pdfs? It's more friendly for the users to see it online.

**Comment by mfherbst** [comment]
Nah but we can build them and put them automatically on gh-pages :smile:

**Comment by mfherbst** [comment]
I made a few cosmetic changes ... let me know what you think.

**Comment by antoine-levitt** [comment]
Great! Sorry about the things I missed...

**Pull request merged**
