### PR TITLE
A few more tweaks for potential mixing

### PR DESCRIPTION
**Pull request by mfherbst**

### CODE REVIEW

**Comment by mfherbst** [comment]
I would merge this, if you are ok with it @antoine-levitt

**Comment by antoine-levitt** [comment]
LGTM!

**Comment by antoine-levitt** [comment]
I just remembered we say
"As usual with MPI printing will be garbled. You can use
DFTK.mpi_master() || (redirect_stdout(); redirect_stderr())"
in the manual. So just do that and don't have these ugly `is_master() && @debug` statements ?

**Comment by mfherbst** [comment]
Well no, because I want to be able to read them in my logs ;)

**Comment by antoine-levitt** [comment]
You can do that with the redirect trick, no?

**Pull request merged**
