### PR TITLE
Switch maximum iteration count to 100

### PR DESCRIPTION
**Pull request by antoine-levitt**
If it doesn't converge in 50 iterations, it's not going to converge in 200

### CODE REVIEW

**Comment by mfherbst** [comment]
100 and I'm in. 50 is too little sometimes.

**Comment by antoine-levitt** [comment]
Really? If 50 is too low then probably the toleranecs are much too low or something is going wrong

**Comment by mfherbst** [comment]
Yes our tolerance selection is not yet great, I agree with that. Let's just go with 100 and see what happens. With 50 I'm simply uncomfortable with respect to practical calculations for now.

**Comment by antoine-levitt** [comment]
OK

**Pull request merged**
