### PR TITLE
Excise symops, part 2

### PR DESCRIPTION
**Pull request by antoine-levitt**
Close https://github.com/JuliaMolSim/DFTK.jl/issues/621 by removing ksymops completely.
Follow-up to https://github.com/JuliaMolSim/DFTK.jl/pull/622.

### CODE REVIEW

**Comment by antoine-levitt** [comment]
This is ready to go.

**Comment by antoine-levitt** [comment]
@mfherbst I split it in two to make it easier to make tests pass, feel free to either review in sequence or just do this one and close the other one.

**Comment by antoine-levitt** [comment]
This is ready to go.

**Comment by mfherbst** [comment]
I'll take a look at merging this once #626 is in as I expect a few annoying conflicts.

**Pull request merged**
