### PR TITLE
Make LDOS mixing the default

### PR DESCRIPTION
**Pull request by mfherbst**
WIP idea for now. Will polish.

### CODE REVIEW

**Comment by mfherbst** [comment]
@antoine-levitt I would merge this now if you agree.

**Comment by antoine-levitt** [comment]
I think the heuristic is reasonable, although temp 0.5 feels too large. I'm still not 100% sure we want to make it the default : on small systems this might account for a non insignificant portion of the computing time, and will not have a large effect. Can you test on eg a small aluminum system?

**Comment by mfherbst** [comment]
Well that depends what one wants the default to do. Right now our default is SimpleMixing, which is equivalent to LdosMixing if you don't use temperature. So for insulators this PR changes nothing. For metals or inhomogeneous systems our current default will fail on larger systems. The question to ask is then (a) do we want a safe default to work out of the box on most cases, but potentially with a runtime overhead or (b) do we want our default to work fast on most systems and then we force the user to choose something else manually in case of failure.  
I would say our usual philosophy of choosing safe defaults is more in line with (a), thus `LdosMixing` by default. Stops no one from switching to Kerker for metals if they want to.

About the timings: For our [magnesium example](https://juliamolsim.github.io/DFTK.jl/stable/examples/metallic_systems/) on most cases I tried the runtime spent on the LDOS is ok for a default method. It sits around 10 - 15% of the time share of the SCF for a number of reasonable settings over different Ecuts and kgrids I tried. Only for strange setups (Ecut=100, only Gamma point) it starts to become a real issue (up to 25% runtime), but I would not consider that too relevant.

About the maximal temperature: That is just a conservative safe-guard. On all calculations I did the maximal temperature was 0.25. My idea was to have this cap for cases you want to go to really high smearing temperatures (i.e. beyond 1e-2) to aid convergence.

**Comment by mfherbst** [comment]
Also we could still gain a bit of time by forwarding guesses to the next SCF step and by more carefully tuning the convergence of the gmres ... I have not really played with that so far.

**Comment by antoine-levitt** [comment]
I'm not completely sure; since the LDOS at the initial guess might be completely stupid there's the risk that it blows up for no reason. OTOH we do want people to try this out, so why not!

**Comment by mfherbst** [comment]
Yes indeed. Getting more people to try it would be one of my hopes as well.

**Pull request merged**
