### PR TITLE
Allow passing Ecut as a keyword argument

### PR DESCRIPTION
**Pull request by mfherbst**
Also makes the compiler emit a deprecation warning (if explicitly turned on) about the old interface being deprecated now.

### CODE REVIEW

**Comment by antoine-levitt** [comment]
Ah you beat me to it, I was just doing this now

**Comment by antoine-levitt** [comment]
I had a
```
## Note the implicit passing of keyword arguments here:
## this is equivalent to PlaneWaveBasis(model; Ecut=Ecut, kgrid=kgrid)
```
in tutorial.md because that might be confusing to new julia users

**Comment by mfherbst** [comment]
Sorry ... I thought it was clear in the comment I left that I would do it.

**Comment by mfherbst** [comment]
good point

**Comment by antoine-levitt** [comment]
There's a bunch of other places we could replace the pattern X=X (or X = X) by X, but it has been too long since I used regexpes

**Comment by mfherbst** [comment]
Yeah, I know, but I suggest we just fix it when we find it.

**Comment by antoine-levitt** [comment]
Yup, just might have been a good candidate while we were search&replacing stuff

**Pull request merged**
