### PR TITLE
Fix normalization of wavefunctions

### PR DESCRIPTION
**Pull request by antoine-levitt**
@azadoks Do you agree? The wavefunctions are not in units of energy, so there should not be a factor of 2 here.

### CODE REVIEW

**Comment by mfherbst** [comment]
@azadoks  ping :smile:

**Comment by azadoks** [comment]
Ah yes, my bad!

**Comment by antoine-levitt** [comment]
I don't understand your comment, is the current version (with fix in) correct?

**Comment by azadoks** [comment]
I think the factor of two needs to go, but we should also probably be normalizing the wavefunctions by their norm. Abinit does `chi ./= sqrt.(integrate(r, chi.^2))` where `chi` is the data from the file (i.e. with the factor of `r` included). QE does the same thing, but it also sets the occupations for any wavefunctions which have a norm `< 1e-8` to a small negative number so that they are not used in the initial guess wavefunction.

**Comment by antoine-levitt** [comment]
OK, I'll open an issue

**Pull request merged**
