### PR TITLE
Crude import of some material from DFTK school

### PR DESCRIPTION
**Pull request by mfherbst**
Because the stuff becomes too outdated otherwise to be useful.

### CODE REVIEW

**Comment by mfherbst** [comment]
@antoine-levitt Probably can be improved at many places, but any objections in merging the current state to have it display ?

My idea was to then get students to use this to learn about DFTK and submit PRs with their fixes when needed.

**Comment by antoine-levitt** [comment]
Sure, but can you split categories for DFTK tutorial (what we have now, which basically assumes people have a reasonable idea of DFT/condensed matter) and general (CM/DFT) tutorials?

**Comment by mfherbst** [comment]
Good idea. Maybe like a getting started and a background section ?

**Comment by antoine-levitt** [comment]
Yup!

**Pull request merged**
